import streamlit as st

st.set_page_config(
    page_title="Dilytics Supply Chain AI",
    layout="wide"
)

# ============================================================
# CSS
# ============================================================

st.markdown("""
<style>

    /* Remove Streamlit default spacing */
    .block-container {
        padding-top: 20px !important;
        padding-left: 30px !important;
        padding-right: 30px !important;
    }

    /* Module selector container */
    .module-container {
        width: 230px;
        margin-bottom: 25px;
    }

    /* Module label */
    .module-label {
        font-size: 13px;
        font-weight: 600;
        color: #12284f;
        margin-bottom: 6px;
    }

    /* Selectbox */
    div[data-testid="stSelectbox"] {
        width: 230px;
    }

    div[data-testid="stSelectbox"] > div {
        border-radius: 7px !important;
    }

    div[data-testid="stSelectbox"] [data-baseweb="select"] {
        min-height: 42px;
        border: 1px solid #cfd9e8;
        border-radius: 7px;
        background: white;
    }

    div[data-testid="stSelectbox"] [data-baseweb="select"]:hover {
        border-color: #0754d8;
    }

    div[data-testid="stSelectbox"] [data-baseweb="select"] > div {
        color: #12284f;
        font-size: 14px;
        font-weight: 600;
    }

    /* Remove label generated by Streamlit */
    div[data-testid="stSelectbox"] label {
        display: none;
    }

</style>
""", unsafe_allow_html=True)


# ============================================================
# MODULE DROPDOWN
# ============================================================

st.markdown("""
<div class="module-container">
    <div class="module-label">
        Module
    </div>
</div>
""", unsafe_allow_html=True)


module = st.selectbox(
    "Module",
    [
        "Supply Chain",
        "Inventory",
        "Purchase Orders",
        "Shipments & Deliveries",
        "Suppliers",
        "Warehouses",
        "Products",
        "Analytics & Reports"
    ],
    index=0,
    label_visibility="collapsed"
)


# ============================================================
# SHOW SELECTED MODULE
# ============================================================

st.write(f"Selected module: **{module}**")
